FROM alpine:3.19.1
# 替换成国内的阿里云源
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
# 更新一下源,并安装软件
RUN apk update && apk add curl vim openssh-client busybox-extras drill net-tools tzdata
# 配置时区。tzdata的作用是配置时区
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo "Asia/Shanghai" > /etc/timezone
# 镜像默认的命令
CMD ["/bin/sh"]